### ISSUE TITLE
API Key support

### ISSUE THREAD

**Issue by zingbats** [kellydunn/golang-geo#34]
Hello, 

Not sure if its an issue or if its my shoddy attempt at using the API, but I don't see support for adding an API key to the end of the urls here. Is that something you are interested in supporting? I could add if so.

**Comment by kellydunn** [comment]
I'd gladly welcome that support!  I recall a few people on a [reddit thread](http://www.reddit.com/r/golang/comments/23jxcm/geodude_a_tiny_commandline_tool_for_geocoding/cgygnn1) mentioning that they'd enjoy it :smile: 

Did you have a particular geocoder in mind?

**Comment by zingbats** [comment]
I had all the geocoders in mind :) I made a pull request. Thanks for writing this, its a great help and has been a really good introduction to Golang for me.

**Comment by kellydunn** [comment]
Merged in as a part of v0.5.4!
