### ISSUE TITLE
finding all stored locations within a 20 KM of a GPS point

### ISSUE THREAD

**Issue by gedw99** [kellydunn/golang-geo#49]
could you advise me if this library can so his.

I dont need to use the SQL functionality for now. i just need to do it all in memory in the middle tier.

i have every users gps location.
I have a event, for which i have the GPS location.

So i need to write  a job that searches for any users location, within 20 km of the Event location.

The advantage of this is that i can do all this without having to use google maps APi and all that

**Comment by kellydunn** [comment]
Heya, @gedw99 !

> I dont need to use the SQL functionality for now. i just need to do it all in memory in the middle tier.
>
> i have every users gps location.
> I have a event, for which i have the GPS location.
>
> So i need to write a job that searches for any users location, within 20 km of the Event location

Currently, the `SQLMapper` is the only implementation of the [`Mapper`](https://github.com/kellydunn/golang-geo/blob/master/mapper.go) interface, which provides the ability to find users within that location.

I do have plans to create an in-memory implementation in a `v1.0.0` release using some type of spatial indexing data structure, like a [RTree](https://en.wikipedia.org/wiki/R-tree), but it has yet to be implemented here.

Unfortuantely, this lib cannot do this for you, but if you wish to use some of the benefits of the library, you could create an implementation of a `Mapper` for now and use it to query for things in memory.  You might be able to port some of the sql logic [here](http://www.movable-type.co.uk/scripts/latlong-db.html) to a more dictionary based search pattern.

**Comment by gedw99** [comment]
Thanks for the response.
Mhh. Sounds like II would be using a Cadillac for something that needs abicycle.

So, i will see what else is out there...

**Comment by kellydunn** [comment]
@gedw99 good luck in your searches!  I'll try to update this ticket when the new functionality comes to life :)

closing for now :)
