### ISSUE TITLE
Error trying to install the package through go get

### ISSUE THREAD

**Issue by guile** [kellydunn/golang-geo#50]
```
user@FRODO /d/goworkspace/bin
$ go get github.com/kellydunn/golang-geo
# cd D:\goworkspace\src\github.com\kylelemons\go-gypsy; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/kylelemons/go-gypsy/yaml: exit status 1
```
![image](https://cloud.githubusercontent.com/assets/82899/10372638/64e82294-6e06-11e5-9c0d-69d462e7cd66.png)

**Comment by kellydunn** [comment]
Interesting; using `go get github.com/kellydunn/golang-geo` works as expected for me on OSX and linux, just tested it.    

I don't currently have access to a Windows VM or windows machine at the moment, but it seems odd to me that the go get tool wouldn't be working as expected here.

What version of go are you using?

**Comment by guile** [comment]
thx for responding.. using go1.5.1 (with git 1.9.5 also installed on the maschine) - the most recent available windows binary

**Comment by kellydunn** [comment]
Super odd.  I'm also running go 1.5.1:

```
$ go version
go version go1.5.1 darwin/amd64
```

Could it be related to git?  I'm using git version 2.4.6

```
$ git --version
git version 2.4.6
```

Not sure if this helps, but it looks like some other windows gophers were experiencing this issue earlier this year:

https://groups.google.com/forum/#!topic/skicka-users/dF-tWNommEo

**Comment by kellydunn** [comment]
@guile any luck?  I suspect it might have to deal with your underlying `git` installation.

**Comment by guile** [comment]
posted about the issue on other boards, but no reply this far. am manually creating the folder structure and copy-pasting go files for needed libraries. :(

**Comment by kellydunn** [comment]
@guile I know it's been a while, but was there any updates on this issue?  Are you able to install `golang-geo` through the `go get` tool on your system?  Can you install other libs?

**Comment by guile** [comment]
@kellydunn good to see you are still around and concerned. 
just tried a fresh install and it worked without issues. haven't been able to figure out why i was getting this earlier error. but as long as it works at my end, i will consider it solved :)
Present config: Git 2.7.1 / go1.5.3

**Comment by kellydunn** [comment]
@guile thanks for updating!
